//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stencil.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbSubscription
    {
        public System.Guid subscription_id { get; set; }
        public System.Guid brand_id { get; set; }
        public System.Guid product_id { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
